# hatch.config.yaml
# Configuration file for HatchEngine projects

projectName: "My First Puzzle" # Changed from project.name for simplicity with current parser
version: "0.1.0"
canvasId: "gameCanvas" # The ID of the HTML canvas element to use
gameWidth: 800             # Default width of the game canvas
gameHeight: 600            # Default height of the game canvas
initialScene: TestScene # Specify the initial scene to load, capitalized
assetManifest: assets/asset-manifest.json # Added for AssetManager
showDebugInfo: true    # Explicitly enable debug info via config

# The following are original, more complex configurations, kept for reference
# but the simple parser in current main.js templates won't use them deeply.
project_details: # Renamed to avoid conflict if parser just takes first part of project.name
  name: "My First Puzzle"
  version: "0.1.0"
  # description: "A simple puzzle game built with HatchEngine."
  # authors: ["Your Name"]

engine_settings: # Renamed
  canvasId_detail: "gameCanvas"
  width_detail: 800
  height_detail: 600
  initialScene_detail: testScene
  showDebugInfo_detail: true
  # targetFps: 60
  # rendering:
    # backend: "canvas2d"
    # antiAlias: true
  # audio:
    # enable: true
    # defaultVolume: 0.8

# Asset manager configuration (Example)
assets_config: # Renamed
  basePath: "assets/"
  manifest_detail: "asset-manifest.json"
  # preload:
    # - "images/spritesheet.png"
    # - "audio/background_music.mp3"

# Scene manager configuration (Example)
scenes_config: # Renamed
  initialScene_detail2: "mainMenu"
  # sceneList:
    # - id: "mainMenu"
      # path: "scenes/MainMenuScene.js"
    # - id: "level1"
      # path: "scenes/Level1Scene.js"

game_config: # Renamed
  difficulty: "normal"
  # player:
    # initialHealth: 100
    # speed: 5
  # levels:
    # total: 3
    # unlockType: "sequential"

input_config: # Renamed
  # keybindings:
    # moveUp: "KeyW"
    # moveDown: "KeyS"
    # action: "Space"
  # mouseSensitivity: 1.0

devServer_config: # Renamed
  port: 3000
  # openBrowser: true

build_config: # Renamed
  outputDir: "dist/"
  # minify: true
  # sourceMaps: false
